package org.example;

import java.math.BigInteger;

public abstract class Operator {
    String name;
    public Operator() {
        name = "Default";
    }

    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.add(b);
        return a;
        //just for example
    }
}

//todo make this code autogenerated
class Addition extends Operator {
    Addition() {
        name = "+";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.add(b);
        return a;
    }
}

class Substraction extends Operator {
    Substraction() {
        name = "-";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.subtract(b);
        return a;
    }
}

class Multiplication extends Operator {
    Multiplication() {
        name = "*";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.multiply(b);
        return a;
    }
}

class Division extends Operator {
    Division() {
        name = "/";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.divide(b);
        return a;
    }
}

class Pow extends Operator {
    Pow() {
        name = "^";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.pow(b.intValue());
        return a;
    }
}
