package org.example;

import java.math.BigInteger;

import org.operator.Operator;

//todo make this code autogenerated
class Addition extends Operator {
    public Addition() {
        name = "+";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.add(b);
        return a;
    }
}

class Substraction extends Operator {
    public Substraction() {
        name = "-";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.subtract(b);
        return a;
    }
}

class Multiplication extends Operator {
    public Multiplication() {
        name = "*";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.multiply(b);
        return a;
    }
}

class Division extends Operator {
    public Division() {
        name = "/";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.divide(b);
        return a;
    }
}

class Pow extends Operator {
    public Pow() {
        name = "^";
    }

    @Override
    public BigInteger apply(BigInteger a, BigInteger b) {
        a = a.pow(b.intValue());
        return a;
    }
}
